config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :chickens, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create, :destroy]
  end

  resources :bookings, only: [:index, :update, :show]
  resources :users, only: [:index, :update, :show, :destroy]

  # get "chickens/dashboard", to: "chickens#dashboard", as: "dashboard"

  resources :conversations do
  resources :messages
    end

end

app/models/chicken.rb
class Chicken < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true, uniqueness: true
  validates :age, presence: true
  validates :egg_volume, presence: true
  validates :photo, presence: true
  validates :description, presence: true
  validates :price, presence: true

end

app/controllers/chickens_controller.rb
class ChickensController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_chicken, only: [:show, :edit, :update, :destroy]

  def index
    # PUNDIT:
    @chickens = policy_scope(Chicken.geocoded)

    # GEOMAP:
    # @chickens = Chicken.geocoded
    @markers = @chickens.map do |chicken|
      {
       lat: chicken.latitude,
       lng: chicken.longitude,
       image_url: helpers.asset_url('logo1.png'),
       infoWindow: render_to_string(partial: "info_window", locals: { chicken: chicken })
      }
    end
  end

  def show
    @booking = Booking.new
    authorize @chicken
  end

  def new
    @chicken = current_user.chickens.new
    authorize @chicken
  end

  def create
    @chicken = current_user.chickens.new(chicken_params)
    authorize @chicken
    # @chicken.price = @chicken.price * 100 ==> is it still necessary to keep this as a comment?
    # @chicken.user_id = User.first.id ==> comment this line because doesn't work

    if @chicken.save!
      redirect_to chicken_path(@chicken)
    else
      render :new
      # redirect_to chicken_new_path
    end
  end

  def edit
    authorize @chicken
  end

  def update
    authorize @chicken

    if @chicken.update(chicken_params)
      redirect_to chicken_path(@chicken)
    else
      render :edit
    end
  end

  def destroy
    authorize @chicken

    @chicken.destroy

    redirect_to chickens_path
  end

  private

  def chicken_params
    params.require(:chicken).permit(:name, :address, :age, :price, :egg_color, :egg_volume, :description, :photo)
  end

  def set_chicken
    @chicken = Chicken.find(params[:id])
  end
end

app/views/chickens/_form.html.erb
<%= simple_form_for @chicken do |f| %>
  <%= f.input :name, wrapper_html: {class: "eggbnb-inputs"}  %>
  <div class="flexbox-input-group">
    <%= f.input :age, wrapper_html: {class: "eggbnb-inputs"} %>
    <%= f.input :price,
                hint: ("Please add your price in dollars"),
                wrapper_html: {class: "eggbnb-inputs"}%>
  </div>
  <div class="flexbox-input-group">
    <%= f.input :egg_volume, wrapper_html: {class: "eggbnb-inputs"} %>
    <%= f.input :egg_color,
                 collection: [ "white", "brown", "blue", "green", "pink" ],
                 wrapper_html: {class: "eggbnb-inputs"} %>
  </div>
  <%= f.input :description, wrapper_html: {class: "eggbnb-inputs"} %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

    <%= f.button :submit, value: "Done", class: 'btn btn-lg btn-primary big-btn-form' %>
<% end %>

app/views/chickens/_info_window.html.erb
<h2> <%=chicken.name %>

</h2>

app/views/chickens/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="form-container">
      <h1>Update your chicken</h1>

      <%= render 'form', chicken: @chicken %>

    </div>
  </div>
  </div>
</div>

app/views/chickens/index.html.erb
<div class="banner-content">
  <%#= link_to "Add a chicken", new_chicken_path, class: "btn btn-primary btn-lg btn-block" %>
</div>

<div class="chickens-container">

  <div class="left-column">
    <div class="chicken-index">

      <div class="chickens-header">
        <h2>All the chicken available in Montreal</h2>
      </div>

      <div class="cards">
        <% @chickens.each do |chicken| %>

          <div class="chicken-card">
            <a href= <%= chicken_path(chicken) %> >
              <% if chicken.photo? %>
                <% background_url = cl_image_path chicken.photo, width: 400, height: 500, crop: :fill %>
              <% else %>
                <% background_url = 'https://images.unsplash.com/photo-1501200291289-c5a76c232e5f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2781&q=80' %>
              <% end %>
              <div class= "chicken-card-total">
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= background_url %>');">
                  <div class="card-description">
                    <h2><strong><%=chicken.name%></strong></h2>
                  </div>
                </div>
                <span class="chicken-card-price">$<%= chicken.price %> /day</span>
                <p class="chicken-card-egg-volume"><%= chicken.egg_volume %> egg/day</p>
              </div>
            </a>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/chickens/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="form-container">
      <h1>Share your chicken with Montrealers</h1>


<%= simple_form_for @chicken do |f| %>
  <%= f.input :name, wrapper_html: {class: "eggbnb-inputs"}  %>
  <div class="flexbox-input-group">
    <%= f.input :age, wrapper_html: {class: "eggbnb-inputs"} %>
    <%= f.input :price,
                hint: ("Please add your price in dollars"),
                wrapper_html: {class: "eggbnb-inputs"}%>
  </div>
  <div class="flexbox-input-group">
    <%= f.input :egg_volume, wrapper_html: {class: "eggbnb-inputs"} %>
    <%= f.input :egg_color,
                 collection: [ "white", "brown", "blue", "green", "pink" ],
                 wrapper_html: {class: "eggbnb-inputs"} %>
  </div>
  <%= f.input :description, wrapper_html: {class: "eggbnb-inputs"} %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

    <%= f.button :submit, value: "Done", class: 'btn btn-lg btn-primary big-btn-form' %>
<% end %>
    </div>
  </div>
  </div>
</div>

app/views/chickens/show.html.erb
<div class="container">
  <div class="master-container">

  <div class="info-column">
    <%= cl_image_tag @chicken.photo, height: 250, width: 500, crop: :fill %>
    <div class="information">
      <h3><%= @chicken.name %></h3>
      <span>eggs per day:</span>
      <% @chicken.egg_volume.times do %>
        <i class="fas fa-egg <%= @chicken.egg_color %>"></i>
      <% end %>
      <div>egg color: <%= @chicken.egg_color %></div>
      <p>price per day: $<%= @chicken.price %></p>
      <% if current_user == nil %>
  <div><%= link_to "Book", new_user_session_path, class: "btn btn-primary" %></div>
<% elsif current_user != @chicken.user %>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Book</button>
<% end %>
    </div>
  </div>

  <div class="description">
    <h3>Hi, I'm <%= @chicken.name %></h3>
    <p><%= @chicken.description %></p>
    <div class="footer-description">
       <p>Belongs to: <%= @chicken.user.first_name%></p>
      <%= cl_image_tag @chicken.user.photo, height: 50, width: 50, crop: :fill %>
      <p><div><%= link_to "Send message", conversations_path(sender_id: current_user, recipient_id: @chicken.user), method: :post, class: "btn btn-primary" %></div></p>
    </div>
    <br>
    <% if policy(@chicken).edit? %>
    <div><%= link_to "Edit", edit_chicken_path(@chicken), class: "btn btn-primary" %></div>
    <% end %>
    
    <% if policy(@chicken).destroy? %>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal">Delete</button>

    <% end %>
  </div>
  </div>
</div>

</div>




<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Book <strong><%= @chicken.name %></strong></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-container">
        <!-- added styling to upcase form fields and format spacing -->
          <h1>You're one step away from farm fresh eggs...</h1>
        <%= simple_form_for [@chicken, @booking] do |f| %>
          <p><%= f.input :start_date, as: :date, start_year: Date.today.year, order: [:day, :month, :year], html5: true, wrapper_html: {class: "eggbnb-inputs"} %></p>
          <p><%= f.input :end_date, as: :date, start_year: Date.today.year, order: [:day, :month, :year], html5: true, wrapper_html: {class: "eggbnb-inputs"} %></p>
          <p id="booking_price">Price per day: $<%= @chicken.price %></p>
          <p id="total-price-calculated" data-price-per-day = "<%=@chicken.price  %>"> </p>
        <br>
        <p><%= f.button :submit, class: 'btn btn-primary' %></p>
        <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <br>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete <strong><%= @chicken.name %></strong></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to do that?</p>
        <div class="chicken-crazy">
        <%= image_tag "chicken-crazy.gif", alt: "alttext" %>
        </div>
           <div><%= link_to "Delete", chicken_path(@chicken), method: :delete, class: "btn btn-danger" %></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <br>
      </div>
    </div>
  </div>
</div>