config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :chickens, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create, :destroy]
  end

  resources :bookings, only: [:index, :update, :show]
  resources :users, only: [:index, :update, :show, :destroy]

  # get "chickens/dashboard", to: "chickens#dashboard", as: "dashboard"

  resources :conversations do
  resources :messages
    end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :chicken

  validates :start_date, presence: true
  validates :end_date, presence: true

  def price_calculation
    (booking.end_date - booking.start_date) * booking.chicken.price
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
    @my_chickens = @bookings.joins(:chicken).where(chickens: { user: current_user })
    @my_bookings = @bookings.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @chicken = Chicken.find(params[:chicken_id])
    @booking = Booking.new(booking_params)
    @booking.chicken = @chicken
    @booking.user = current_user
    authorize @booking
    if @booking.save!
      redirect_to bookings_path
      flash[:notice] = "Booking successfully created"
    else
       render "chickens/show"
     end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(status: params[:status])
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:id, :start_date, :end_date, :user_id, :chicken_id)
  end
end

app/views/bookings/create.html.erb
<h1>create test page</h1>

<%= link_to "go back to chicken_index", chickens_path %>

<%= simple_form_for(@chicken) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :egg_volume %>
  <%= f.text_field :egg_volume %>

  <%= f.label :egg_color %>
  <%= f.text_field :egg_color %>

   <%= f.label :egg_description %>
  <%= f.text_field :egg_description %>

  <%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
<h1><strong>My Dashboard</strong></h1>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>My bookings</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Booker name</th>
            <th>Chicken owner</th>
            <th>Chicken name</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Price per day</th>
            <th>Total</th>
            <th>Status</th>
            <th>Accept booking</th>
          </thead>
          <% @my_bookings.each do |booking| %>
            <tr>
              <%= link_to booking_path(booking) do %>
                <td><%= booking.user.first_name%>
                <td><%= booking.chicken.user.first_name%>
                <td><%= booking.chicken.name%>
                  <%= cl_image_tag booking.chicken.photo, width: 50, height: 40, crop: :fill %>
                </td>
                <td><%= booking.start_date %></td>
                <td><%= booking.end_date %></td>
                <td>$<%= booking.chicken.price %></td>
                <td>$<%= ( booking.end_date.jd - booking.start_date.jd ) * booking.chicken.price %></td>
                <td><%= booking.status %></td>
                <td><%= link_to "Accept", booking_path(booking, status: "Accepted"), method: :patch%>
                  <%= link_to "Reject", booking_path(booking, status: "Rejected"), method: :patch%>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

<div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>My chickens</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Booker name</th>
            <th>Chicken owner</th>
            <th>Chicken name</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Price per day</th>
            <th>Total</th>
            <th>Status</th>
            <th>Accept booking</th>
          </thead>
          <% @my_chickens.each do |booking| %>
            <tr>
              <%= link_to booking_path(booking) do %>
                <td><%= booking.user.first_name%>
                <td><%= booking.chicken.user.first_name%>
                <td><%= booking.chicken.name%>
                  <%= cl_image_tag booking.chicken.photo, width: 50, height: 40, crop: :fill %>
                </td>
                <td><%= booking.start_date %></td>
                <td><%= booking.end_date %></td>
                <td>$<%= booking.chicken.price %></td>
                <td>$<%= ( booking.end_date.jd - booking.start_date.jd ) * booking.chicken.price %></td>
                <td><%= booking.status %></td>
                <td><%= link_to "Accept", booking_path(booking, status: "Accepted"), method: :patch%>
                  <%= link_to "Reject", booking_path(booking, status: "Rejected"), method: :patch%>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div><%= link_to "Go back to list of chickens", chickens_path, class: "btn btn-primary btn-sm" %></div>

    </div>

app/views/bookings/new.html.erb
<h1>create test page</h1>

<%= link_to "go back to chicken_index", chickens_path %>

<%= simple_form_for(@chicken) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :egg_volume %>
  <%= f.text_field :egg_volume %>

  <%= f.label :egg_color %>
  <%= f.text_field :egg_color %>

   <%= f.label :egg_description %>
  <%= f.text_field :egg_description %>

  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking details</h1>

<% if @booking.status == "Pending" %>
<ul>
<li><%= link_to "Accept", booking_path(@booking, status: "Accepted"), method: :patch%>
</li>
<li>
  <%= link_to "Reject", booking_path(@booking, status: "Rejected"), method: :patch%>
</li>
</ul>
<% else %>
  <p>Your booking has been <%= @booking.status %></p>
<% end %>