config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :chickens, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create, :destroy]
  end

  resources :bookings, only: [:index, :update, :show]
  resources :users, only: [:index, :update, :show, :destroy]

  # get "chickens/dashboard", to: "chickens#dashboard", as: "dashboard"

  resources :conversations do
  resources :messages
    end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_inline.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li>
          <form class="form-inline">
          <label for="">Start Date </label>
          <input class="form-control mr-sm-2" type="date" id="start" name="trip-start" value="2019-08-23" min="2019-01-01" max="2050-12-31">
          <label for="">End Date </label>
          <input class="form-control mr-sm-2" type="date" id="start" name="trip-start" value="2019-08-23" min="2019-01-01" max="2050-12-31">
          <input class="form-control mr-sm-2" type="address" placeholder="Where are you?" aria-label="Search">
          <div><%= link_to "book a chicken", chickens_path, class: "btn btn-primary btn-navbar" %></div>
          </form>
        </li>
        <li>
          <div><%= link_to "list a chicken", new_chicken_path, class: "btn btn-primary btn-navbar" %></div>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My messages", conversations_path, class: "dropdown-item" %>
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li>
          <form class="form-inline">
          <label for="">Start Date </label>
          <input class="form-control mr-sm-2" type="date" id="start" name="trip-start" value="2019-08-23" min="2019-01-01" max="2050-12-31">
          <label for="">End Date </label>
          <input class="form-control mr-sm-2" type="date" id="start" name="trip-start" value="2019-08-23" min="2019-01-01" max="2050-12-31">
          <input class="form-control mr-sm-2" type="address" placeholder="Where are you?" aria-label="Search">
          <div><%= link_to "book a chicken", chickens_path, class: "btn btn-primary btn-navbar" %></div>
          </form>
        </li>
        <li>
          <div><%= link_to "list a chicken", new_chicken_path, class: "btn btn-primary btn-navbar" %></div>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>